name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build geosite
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go run -v .
      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geosite.db > geosite.db.sha256sum
      - name: Create a release
        if: steps.build.outputs.skip != 'true'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          name: ${{ steps.build.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            geosite.db
            geosite.db.sha256sum